# Generated by Django 2.2.16 on 2021-09-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210927_2009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='default',
        ),
    ]
